trigger:
    branches:
        - main
        - dev
        - qa
    path:
        include:
            - backend/*
        exclude:
            - frontend/*
            - infrastructure/*
    batch: true

pr:
    branches:
        - main
        - dev
        - qa
    path:
        include:
            - backend/*
        exclude:
            - frontend/*
            - infrastructure/*

pool:
    vmImage: "ubuntu-latest"

variables:
    buildConfiguration: 'Release'

steps:
    - task: DotNetCoreCLI@2
      inputs:
          command: 'restore'
          feedsToUse: 'select'
          vstsFeed: 'my-vsts-feed' # A series of numbers and letters

    - task: DotNetCoreCLI@2
      inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
      displayName: 'dotnet build $(buildConfiguration)'
